# Generated by Django 3.2 on 2021-06-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_admin_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='stations_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
    ]
