# Generated by Django 3.2 on 2021-06-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_slots_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots_table',
            name='booking_status',
            field=models.CharField(default='avilable', max_length=15),
        ),
        migrations.AddField(
            model_name='slots_table',
            name='chrging_status',
            field=models.CharField(default='active', max_length=15),
        ),
    ]
