# Generated by Django 3.2 on 2021-06-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20210622_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phoneno', models.BigIntegerField()),
                ('request', models.CharField(default='pending', max_length=15)),
            ],
        ),
    ]
