# Generated by Django 3.2 on 2021-06-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_user_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots_table',
            name='chrging_status',
            field=models.CharField(default='inactive', max_length=15),
        ),
    ]
