# Generated by Django 3.2 on 2021-06-26 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_history_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots_table',
            name='station_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.stations_table'),
        ),
    ]
