# Generated by Django 3.2 on 2021-06-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_slots_table_slotno'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_table',
            name='slotno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
